// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package idp

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type User struct {
	ID            string    `json:"id"`
	Email         string    `json:"email"`
	PasswordHash  string    `json:"passwordHash"`
	EmailVerified bool      `json:"email_verified"`
	GivenName     *string   `json:"given_name"`
	FamilyName    *string   `json:"family_name"`
	MiddleName    *string   `json:"middle_name"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type UserInput struct {
	Email      string  `json:"email"`
	Password   string  `json:"password"`
	GivenName  *string `json:"given_name"`
	FamilyName *string `json:"family_name"`
	MiddleName *string `json:"middle_name"`
}

type UserGender string

const (
	UserGenderMale   UserGender = "male"
	UserGenderFemale UserGender = "female"
)

func (e UserGender) IsValid() bool {
	switch e {
	case UserGenderMale, UserGenderFemale:
		return true
	}
	return false
}

func (e UserGender) String() string {
	return string(e)
}

func (e *UserGender) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserGender(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserGender", str)
	}
	return nil
}

func (e UserGender) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
