// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package idp

import (
	"time"
)

type User struct {
	ID            string    `json:"id" gorm:"primary_key"`
	Email         string    `json:"email" gorm:"unique"`
	PasswordHash  string    `json:"passwordHash"`
	EmailVerified bool      `json:"email_verified"`
	UpdatedAt     time.Time `json:"updated_at"`
}
